[package]
name = "acpi"
version = "0.1.0"
edition = "2021"

[features]
default = ["alloc"]
alloc = []

[dependencies]
bitflags = "2.3"
libsa = { git = "https://github.com/bolt-os/libsa.git" }
log = "*"
